[package]
name = "blockchain_rust"
version = "0.1.0"
authors = ["levequel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "blockchain_rust"
path = "src/main.rs"
